## code to prepare `lipid_class_order` dataset goes here

# Lipid class order
lipid_class_order <- c("sample",
                       "sample_input",
                       "PC", "aPC", "ePC",
                       "LPC",
                       "PE", "aPE", "ePE",
                       "LPE",
                       "plPE16-0", "PE P-16-0", "PE P-16_0", "PE P-16:0",
                       "plPE18-1", "PE P-18-1", "PE P-18_1", "PE P-18:1",
                       "plPE18-0", "PE P-18-0", "PE P-18_0", "PE P-18:0",
                       "PS", "aPS", "ePS",
                       "LPS",
                       "PI", "aPI", "ePI",
                       "LPI",
                       "PG", "aPG", "ePG",
                       "LPG",
                       "PA", "aPA", "ePA",
                       "LPA",
                       "SM",
                       "PECer", "PE-Cer", "CerPE", "Cer-PE",
                       "Cer",
                       "tCer", "t-Cer",
                       "HexCer", "GlcCer",
                       "Hex2Cer", "LacCer",
                       "Hex3Cer",
                       "SGalCer", "Sulfatides", "Sulf",
                       "GM3", "GM2", "GM1",
                       "EE",
                       "SAA", "Ergo",
                       "CA", "Chol",
                       "sterols", "Sterols",
                       "CE",
                       "DAG", "DG",
                       "TAG", "TG",
                       "sum [uM]",
                       "sum [pmol]")

usethis::use_data(lipid_class_order, overwrite = TRUE)
