---
title: "Dev page for Shiny"
editor_options:
  chunk_output_type: console
output:
  html_document:
    df_print: paged
---


```{r load packages & functions, message=FALSE, warning=FALSE}
devtools::load_all()
library(dplyr)
```


```{r}
path <- system.file("extdata", package = "shinylipidcountr")
rawdata <- read_lipidview_files(path, clean_samples = FALSE)

metadata <- read_metadata(path, clean_samples = FALSE)
```


```{r}
data <- rawdata %>% 
  join_metadata(metadata) %>%
  join_istd_means() %>%
  intensity_to_pmol() %>%
  blank_sub() %>% 
  impute_rf() %>%
  apply_rf() %>%
  pmol_to_uM() #%>%
  #sum_same_species()

# removes "x" in column "sample" & "sample_name". If sample names start with a 
# numeric, janitor puts automatically "x" before the sample name.
data <- data %>% mutate(sample = stringr::str_remove(sample, "x"),
                        sample = forcats::fct_inorder(species, ordered = NA),
                        sample_name = stringr::str_remove(sample_name, "x"),
                        sample_name = forcats::fct_inorder(species, ordered = NA))
```


```{r}
read_lipidxplorer_files <- function(path){
  
    readr::read_csv(path, show_col_types = FALSE, na = c("", "None")) %>%
    dplyr::filter(Class != "###") %>% 
    dplyr::select(Class, ChemicalSpecies, MolecularSpecies, LipidCategory, Mass, 
                  tidyselect::starts_with("Intensity"), 
                  tidyselect::starts_with("FattyAcidIntensity"))
  
}

clean_lipidxplorer_files <- function(rawdata, clean_samples = TRUE){
  
  if(clean_samples == TRUE){
    
    data <- rawdata %>% 
      janitor::clean_names() %>%
      tidyr::pivot_longer(
        cols = c(-class, -chemical_species, -molecular_species, -lipid_category,
                 -mass), 
        names_to = "sample", 
        values_to = "intensity")
    
    # separate fullms- and ms2-intensities
    # ms1 data in column 'intensity'
    # ms2 data in column 'fa_intensity'
    data <- data %>% 
      mutate(fatty_acid_comp = ifelse(stringr::str_detect(sample, "fatty"),
                                      "fa_intensity", "intensity"),
             sample = stringr::str_remove(sample, "fatty_acid_")) %>%
      tidyr::pivot_wider(id_cols = c(class, chemical_species, molecular_species,
                                     lipid_category, mass, sample),
                         names_from = fatty_acid_comp, values_from = intensity,
                         names_repair = "check_unique")
    
    # remove unnecessary strings from sample names for better reading 
    data <- data %>%  
      mutate(sample = stringr::str_remove(sample, "intensity_"),
             sample = stringr::str_remove(sample, "_s_mz_xml"))
    
  } else if(clean_samples == FALSE){
    
    data <- rawdata %>% 
      tidyr::pivot_longer(
        cols = c(-Class, -ChemicalSpecies, -MolecularSpecies, -LipidCategory,
                 -Mass),
        names_to = "Sample",
        values_to = "Intensity") %>% 
      janitor::clean_names()
    
    # separate fullms- and ms2-intensities
    # ms1 data in column 'intensity'
    # ms2 data in column 'fa_intensity'
    data <- data %>% 
      mutate(fatty_acid_comp = ifelse(stringr::str_detect(sample, "Fatty"),
                                      "fa_intensity", "intensity"),
             sample = stringr::str_remove(sample, "FattyAcid")) %>%
      tidyr::pivot_wider(id_cols = c(class, chemical_species, molecular_species,
                                     lipid_category, mass, sample),
                         names_from = fatty_acid_comp, values_from = intensity,
                         names_repair = "check_unique")
    
    # remove unnecessary strings from sample names for better reading 
    data <- data %>%  
      mutate(sample = stringr::str_remove(sample, "Intensity:"),
             sample = stringr::str_remove(sample, "-s.mzXML"))
    
  }
  
  # enhance internal standard species name with 'IS', so the function 
  # 'join_istd_means()' can detect internal standards
  data <- data %>%
    mutate(chemical_species = ifelse(lipid_category == "Internal standard",
                                     paste0("IS ", chemical_species), 
                                     chemical_species),
           molecular_species = ifelse(lipid_category == "Internal standard", 
                                      paste0("IS ", molecular_species), 
                                      molecular_species))
  # remove class name from species for better reading
  data <- data %>%  
    rename(species = chemical_species) %>% 
    mutate(species = ifelse(class != species,
                            stringr::str_remove_all(species, paste0(class, " ")),
                            species))
  
  return(data)
}
```


```{r sample match for LV and LX data}
lx_data <-  #input$file_lx$datapath %>%
  path_to_csv %>% 
          read_lipidxplorer_files() %>%
          clean_lipidxplorer_files(clean_samples = FALSE) %>%
          dplyr::rename(scan_name = molecular_species) %>%
          dplyr::select(class, species, scan_name, sample, intensity)

####
lv_data <-system.file("extdata", package = "shinylipidcountr") %>%
  list_txt_files() %>% 
  read_txt_files() %>%
  shinylipidcountr::clean_txt_files(clean_samples = FALSE) %>%
  tidyr::pivot_longer(
    cols = c(-species, -class, -scan_name),
    names_to = "sample",
    values_to = "intensity")

get_samples(lv_data)
get_samples(lx_data)
```


```{r blank sub}
blank_sub <- function(raw_data){
  
  blank_data <- raw_data %>%
    dplyr::filter(sample %in% blank) %>% 
    dplyr::select(class, species, blank = sample, kon_pmol = pmol,
                  if(any(colnames(raw_data) == "scan_name")){"scan_name"})
  
  dplyr::left_join(raw_data, blank_data, by = c("class", "species", "blank",
                                                if(any(colnames(raw_data) == "scan_name")){"scan_name"})) %>%
    dplyr::mutate(pmol_corr = pmol - kon_pmol,
                  pmol_corr = ifelse(pmol_corr < 0, 0, pmol_corr)) %>%
    dplyr::filter(!sample %in% blank) %>% 
    dplyr::select(-blank, -kon_pmol)

}
```


```{r}
raw_data <- system.file("extdata", package = "shinylipidcountr") %>% 
  list_txt_files() %>% 
  read_txt_files() %>%
  clean_txt_files(clean_samples = FALSE) %>%
  tidyr::pivot_longer(
    cols = c(-species, -class, -scan_name),
    names_to = "sample",
    values_to = "intensity") %>% 
  join_metadata(metadata) %>%
  join_istd_means() %>%
  intensity_to_pmol()

meta_queue <- metadata %>%
    dplyr::filter(class == "blank") %>%
    dplyr::select(-class, -rf_values) %>%
    tidyr::pivot_longer(everything(),
                        names_to = "sample",
                        values_to = "blank")

exp_queue <- raw_data %>% 
  select(sample) %>% 
  unique()

```


```{r}
## LipidXplorer
raw_data_lx <-  
  system.file("extdata", "lx-out.csv", package = "shinylipidcountr") %>% 
  read_lipidxplorer_files() %>%
  clean_lipidxplorer_files(clean_samples = FALSE)

## LipidView
raw_data_lv <- 
  system.file("extdata", package = "shinylipidcountr") %>% 
  list_txt_files() %>%
  read_txt_files() %>%
  clean_txt_files(clean_samples = FALSE) %>% 
  tidyr::pivot_longer(
    cols = c(-species, -class, -scan_name),
    names_to = "sample",
    values_to = "intensity")


# If samples names from LipidView and LipidXplorer are not the same
# check_sample_names-function will stop the process!
check_sample_names(raw_data_lv, raw_data_lx)

data <- merge_with_lipidview(raw_data_lx, raw_data_lv)
```


```{r}
data <- test_raw_data %>% 
  join_metadata(test_metadata) %>%
  join_istd_means() %>%
  intensity_to_pmol() %>%
  blank_sub() %>% 
  impute_rf(blank_sub = TRUE, kon = "Kon") %>% 
  apply_rf() %>% 
  pmol_to_uM()

raw_data <- test_raw_data %>% 
  join_metadata(test_metadata) %>%
  join_istd_means() %>%
  intensity_to_pmol() %>%
  dplyr::filter(!stringr::str_detect(sample, "Kon A")) %>% 
  blank_sub() 

data_omit_blank <- test_raw_data %>% 
  join_metadata(test_metadata) %>%
  join_istd_means() %>%
  intensity_to_pmol() %>%
  mutate(pmol_corr = pmol) %>%
  select(-blank)
```


```{r blank sub}
blank_sub <- function(raw_data){

  blank_data <- raw_data %>%
    dplyr::filter(sample %in% blank) %>%
    dplyr::select(class, species, blank = sample, kon_pmol = pmol,
                  if(any(colnames(raw_data) == "scan_name")){"scan_name"})
  
  if(nrow(blank_data) == 0){
    stop("No blanks in raw data detected. Look for ", 
         unique(raw_data$blank),
         " in your raw data.")
  }

  dplyr::left_join(raw_data, blank_data, by = c("class", "species", "blank",
                                                if(any(colnames(raw_data) == "scan_name")){"scan_name"})) %>%
    dplyr::mutate(pmol_corr = pmol - kon_pmol,
                  pmol_corr = ifelse(pmol_corr < 0, 0, pmol_corr)) %>%
    dplyr::filter(!sample %in% blank) %>%
    dplyr::select(-blank, -kon_pmol)

}
```


```{r R6 tests}
### R6 LipidomicsData ----------------------------------------------------------
LipidomicsData <- R6::R6Class("LipidomicsData",
                              public = list(
                                data = NULL,
                                rawdata = NULL,
                                metadata = NULL,
                                join_metadata = function(){
                                  # Extract sample input [ul] from meta data
                                  sample_input <- self$metadata %>%
                                    dplyr::filter(class == "sample input") %>%
                                    dplyr::select(-class, -rf_values) %>%
                                    tidyr::pivot_longer(everything(),
                                                        names_to = "sample",
                                                        values_to = "sample_input") %>%
                                    dplyr::mutate(sample_input = as.numeric(sample_input))
                                
                                  sample_groups <- self$metadata %>%
                                    dplyr::filter(class == "group") %>%
                                    dplyr::select(-class, -rf_values) %>%
                                    tidyr::pivot_longer(everything(),
                                                        names_to = "sample",
                                                        values_to = "group")
                                
                                  sample_blanks <- self$metadata %>%
                                    dplyr::filter(class == "blank") %>%
                                    dplyr::select(-class, -rf_values) %>%
                                    tidyr::pivot_longer(everything(),
                                                        names_to = "sample",
                                                        values_to = "blank")
                                  
                                  # Extract internal standard concentrations [pmol]
                                  # and response factors (rf-values) from meta data
                                  standard_input <- self$metadata %>%
                                    dplyr::filter(class != "sample input",
                                                  class != "group",
                                                  # if multi_blank_sub() is in use, it is necessary to remove blank-row
                                                  class != "blank") %>%
                                    tidyr::pivot_longer(
                                      cols = c(-class, -rf_values),
                                      names_to = "sample",
                                      values_to = "standard_input") %>%
                                    dplyr::mutate(standard_input = as.numeric(standard_input))
                                  
                                  # Join metadata
                                  joined_metadata <- standard_input %>%
                                    dplyr::left_join(sample_input, by = "sample") %>%
                                    dplyr::left_join(sample_groups, by = "sample") %>%
                                    dplyr::left_join(sample_blanks, by = "sample")
                                  
                                  # Join raw_data and metadata and keep order for species, sample and groups
                                  self$data <- 
                                    dplyr::left_join(self$rawdata, joined_metadata, by = c("class", "sample")) %>%
                                    dplyr::mutate(species = forcats::fct_inorder(species, ordered = NA),
                                                  sample = forcats::fct_inorder(sample, ordered = NA),
                                                  group = forcats::fct_inorder(group, ordered = NA),
                                                  sample_name = stringr::str_remove(sample, "sample_"),
                                                  sample_name = paste(sample_name, "-", group),
                                                  sample_name = forcats::fct_inorder(sample_name, ordered = NA))
                                }
                              )
                                

)

#LipidomicsData$set("public", "rawdata", test_raw_data)
#LipidomicsData$set("public", "metadata", test_metadata)

test <- LipidomicsData$new()

test$rawdata <- test_raw_data
test$metadata <- dplyr::as_tibble(test_metadata)

test$join_metadata()
test$data <- 1

test$rawdata <- test_raw_data %>% join_metadata(test$metadata)

### R6 MyBankAccount -----------------------------------------------------------

MyBankAccount <- R6::R6Class(
  "MyBankAccount",
  public = list(
    balance = 0,
    deposit = function(x = 0){
      
      cat("Old balance: ", self$balance, "\n")
      
      self$balance <- self$balance + x
      
      cat("New balance: ", self$balance)
      
      invisible(self$balance)
    },
    withdraw = function(x = 0){
      stopifnot((self$balance - x) >= 0, x >= 0)
      
      cat("Old balance: ", self$balance, "\n")
       
      self$balance <- self$balance - x
      
      cat("New balance: ", self$balance)
      
      invisible(self$balance)
    },
    initialize = function(balance) {
      stopifnot(is.numeric(balance), balance >= 0)
      
      self$balance <- balance
    }
  )
)

bank <- MyBankAccount$new(balance = 0)
bank$deposit(10)
bank$withdraw(10)

bank$deposit(10)

bank$balance
bank$withdraw(5)

```


```{r rf}
raw_data <- test_raw_data %>% 
  filter(class == "Chol") %>% 
  join_metadata(test_metadata) %>%
  join_istd_means() %>%
  intensity_to_pmol() %>%
  blank_sub() %>% 
  impute_rf(blank_sub = TRUE, kon = "Kon")

impute_rf <- function(raw_data, blank_sub = TRUE, kon = "kon"){

  if (any(is.na(raw_data$rf_values)) == TRUE){

    # Calculate pmol-values of kon's
    missing_rf <- raw_data %>%
      dplyr::filter(stringr::str_detect(as.character(sample), kon) & is.na(rf_values))

    # blank substraction (depending on blank_sub-argument of function), then calculate response factors
    new_rf <- missing_rf %>%
      dplyr::mutate(rf_values = if(blank_sub == TRUE){
        sample_input / pmol_corr} else {sample_input / pmol}) %>%
      dplyr::group_by(class, species) %>%
      dplyr::summarise(rf_values = mean(rf_values), .groups = "drop")

    # join and unite the calculated rf-values and get rid off kon_b and c.
    # unite()-function merges 2 columns and returns characters.
    # Therefore remove NA-strings and convert back to numeric)
    dplyr::left_join(raw_data,
                     new_rf,
                     by = c("class", "species")) %>%
      tidyr::unite("rf_values",
                   "rf_values.y",
                   "rf_values.x",
                   sep = "",
                   remove = TRUE,
                   na.rm = TRUE) %>%
      dplyr::mutate(rf_values = stringr::str_remove_all(rf_values, "NA"),
                    rf_values = as.numeric(rf_values)) %>%
      # OR-function in str_detect to keep "Kon A" for further processing, but remove all other "Kon"s
      dplyr::filter(!stringr::str_detect(sample, kon))

  } else {
    raw_data
  }

}

stringr::str_detect(snakecase::to_any_case(
        as.character(raw_data$sample)), "kon")
```


```{r openxlsx classplot}
class_plot <- function(data){
  
  plot_data <- data %>%
    dplyr::group_by(class) %>%
    dplyr::mutate(ether = stringr::str_detect(species, "O-"),
                  diacyl = any(ether)) %>%
    dplyr::group_by(class, sample_name, group, ether, diacyl, sample_input) %>%
    dplyr::summarise(uM = sum(uM), .groups = "drop") %>%
    dplyr::mutate(class = ifelse(ether == TRUE, paste0("e", class), class),
                  class = ifelse(diacyl == TRUE & ether == FALSE,
                                 paste0("a", class), class)) %>%
    dplyr::select(-ether, -diacyl) %>%
    dplyr::group_by(sample_name) %>%
    dplyr::mutate(mol_percent = uM * 100 / sum(uM)) %>%
    dplyr::group_by(class, group) %>%
    dplyr::mutate(sd = sd(mol_percent),
                  mean_mol_percent = mean(mol_percent))
  
  plot_data %>% 
    ggplot2::ggplot(ggplot2::aes(x = class,
                                 y = mean_mol_percent,
                                 fill = group)) +
    ggplot2::geom_col(color = "black",
                      width = 0.9,
                      position = ggplot2::position_dodge()) +
    ggplot2::ggtitle("Lipid class profile") +
    ggplot2::xlab("Lipid classes") + 
    ggplot2::ylab("Percentage / total lipids") +
    ggplot2::labs(fill = "") + # removes legend title ("group")
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45),
                   plot.title = ggplot2::element_text(hjust = 0.5)) +
    ggplot2::geom_point(ggplot2::aes(x = class,
                                     y = mol_percent,
                                     fill = group,
                                     color = group),
                        position = ggplot2::position_dodge(0.9),
                        size = 1,
                        shape = 21,
                        fill = "white") +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = mean_mol_percent - sd,
                                        ymax = mean_mol_percent + sd),
                           width = 0.3,
                           size = 0.5,
                           position = ggplot2::position_dodge(0.9)) +
    ggplot2::scale_x_discrete(limits = lipid_class_order[lipid_class_order %in% plot_data$class]) +
    ggplot2::guides(color = "none", size = "none") # removes geom_point-legend
}

class_plot(data)

funs <- c(sum = sum_table,
                ether = ether_table,
                species = species_table,
                species_mean = species_mean_table,
                species_plot = species_plot)

      args <- list(data = data,
                   threshold = 1)

excel_data <-
          unique(data$class) %>%
          purrr::map(~ funs %>% purrr::map(rlang::exec, .x, !!!args)) %>%
          setNames(unique(data$class))

wb <- openxlsx::createWorkbook()
unique(data$class) %>%
          purrr::map(~add_lipidclass_sheet(., excel_data, workbook = wb))

openxlsx::saveWorkbook(wb, paste0("functiontest",".xlsx"), overwrite = TRUE)
```


```{r}

raw_data <- 
  system.file("extdata/LipidView_reports_old", package = "shinylipidcountr") %>%
  list.files(pattern = ".txt", full.names = TRUE) %>%
  as.list() %>% 
  purrr::map(read.table, skip = 1, header = TRUE, sep = "\t", check.names = F) %>% 
  purrr::map(~ dplyr::rename(.[-1, -(2:4)], "mz" = 1, "species" = 2, "scan_name" = 3)) %>% 
  purrr::reduce(merge, all = TRUE, sort = FALSE)

  

raw_data2 <- raw_data %>%
  dplyr::mutate(class = stringr::str_remove_all(species, "IS "),
                class = stringr::str_remove_all(class, "D[0-9]-"),
                class = purrr::map(stringr::str_split(class, " ", n = 2), 1))
              
  
  
  
  dplyr::mutate(species = stringr::str_remove_all(species, "\\+NH4"),
                species = ifelse(
                  class != species,
                  stringr::str_remove_all(species, paste0(class, " ")),
                  species),
                scan_name = stringr::str_remove(scan_name, "\\(-FA "),
                scan_name = stringr::str_remove(scan_name, "\\)"),
                scan_name = stringr::str_remove(scan_name, "\\("))
```


```{r}
raw_data_lv <- 
  # merge
  system.file("extdata", package = "shinylipidcountr") %>%
  list.files(pattern = ".txt", full.names = TRUE) %>%
  as.list() %>% 
  purrr::map(read.table, header = TRUE, sep = "\t", check.names = F) %>%  
  purrr::map(~ dplyr::rename(.[-1,], species = `Sample Name`)) %>% 
  purrr::reduce(merge, all = TRUE, sort = FALSE) %>% 
  # long format
  tidyr::pivot_longer(cols = -species,
                      names_to = "sample",
                      values_to = "intensity") %>% 
  # clean up
  dplyr::mutate(class = stringr::str_extract(species, "(?<=\\().+?(?=\\))"),
                species = stringr::str_remove(species, "\\((.*?)\\)"),
                species = ifelse(
                      class != species,
                      stringr::str_remove_all(species, paste0(class, " ")),
                      species),
                intensity = as.numeric(intensity)) %>% 
  dplyr::select(class, species, tidyr::everything())

test <- raw_data %>% 
  join_metadata(test_metadata) %>% 
  join_istd_means() %>%
  intensity_to_pmol() %>%
  blank_sub() %>% 
  impute_rf(blank_sub = TRUE, kon = "Kon") %>% 
  apply_rf() %>% 
  pmol_to_uM()
```


```{r}
read_lipidview_files <- function(path){
  as.list(path) %>% 
  purrr::map(read.table, header = TRUE, sep = "\t", check.names = F) %>%  
  purrr::map(~ dplyr::rename(.[-1,], species = `Sample Name`)) %>% 
  purrr::reduce(merge, all = TRUE, sort = FALSE)
}

clean_lipidview_files <- function(rawdata){
  # long format
  rawdata %>% 
    tidyr::pivot_longer(cols = -species,
                        names_to = "sample",
                        values_to = "intensity") %>% 
    # clean up
    dplyr::mutate(class = stringr::str_extract(species, "(?<=\\().+?(?=\\))"),
                  species = stringr::str_remove(species, "\\((.*?)\\)"),
                  species = ifelse(
                    class != species,
                    stringr::str_remove_all(species, paste0(class, " ")),
                    species),
                   intensity = as.numeric(intensity)) %>% 
    dplyr::select(class, species, tidyr::everything())
}

data <- system.file("extdata", package = "shinylipidcountr") %>%
  list.files(pattern = ".txt", full.names = TRUE) %>% 
  read_lipidview_files() %>% 
  clean_lipidview_files() %>% 
  join_metadata(test_metadata) %>% 
  join_istd_means() %>%
  intensity_to_pmol() %>%
  blank_sub() %>% 
  impute_rf(blank_sub = TRUE, kon = "Kon") %>% 
  apply_rf() %>% 
  pmol_to_uM()


```

```{r plotly}
# species_plot(data, "PC")
lipid_class <- "SM"
threshold <- 0.5

plot_data <- data %>%
    dplyr::filter(class == lipid_class) %>%
    dplyr::group_by(class, sample, group) %>%
    dplyr::mutate(mol_percent = uM * 100 / sum(uM)) %>%
    dplyr::group_by(species, group) %>%
    dplyr::mutate(sd = sd(mol_percent),
                  mean_mol_percent = mean(mol_percent),
                  ###
                  ###--- to keep width of cols, all values become 0 if < 0.5%
                  mean_mol_percent_filter = dplyr::if_else(mean_mol_percent <= threshold,
                                                           0,
                                                           mean_mol_percent)) %>%
    dplyr::group_by(species) %>%
    dplyr::mutate(sum_filter = sum(mean_mol_percent_filter)) %>%
    dplyr::filter(sum_filter != 0)

gg <- ggplot2::ggplot(plot_data, ggplot2::aes(x = factor(species, levels = plot_data$species %>% unique()),
                                 y = mean_mol_percent,
                                 fill = group)) +
    ggplot2::geom_col(color = "black",
                      width = 0.9,
                      position = ggplot2::position_dodge()) +
    ggplot2::ggtitle(paste(lipid_class, paste0("species profile (> ", threshold ," mol%)"))) +
    ggplot2::xlab("Lipid species") +
    ggplot2::ylab("Mean mol %") +
    ggplot2::labs(fill = "") + # removes legend title ("group")
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45),
                   plot.title = ggplot2::element_text(hjust = 0.5)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = mean_mol_percent - sd,
                                        ymax = mean_mol_percent + sd),
                           width = 0.8,
                           size = 0.05,
                           position = ggplot2::position_dodge(0.9),
                           show.legend = FALSE) +
  ggplot2::guides(color = FALSE, size = FALSE) +
  ggplot2::geom_point(
        ggplot2::aes( y = mol_percent,
                      text = purrr::map(paste('<b>amount:</b>',
                             sprintf("%.2f %%", mol_percent),
                             '<br>',
                             '<b>replicate:</b>',
                             sample),
                       HTML)),
        position    = ggplot2::position_dodge(width = 0.9),
        pch         = 21,
        alpha       = 1,
        color       = "black",
        show.legend = FALSE
      ) # removes geom_point-legend

plotly::ggplotly(gg, tooltip = "text") %>%
  plotly::style(
          marker.size = 3,
          marker.line = list(width = 0.5)) %>% 
  plotly::layout(
    xaxis = list(tickfont = list(size = 15)),
    yaxis = list(tickfont = list(size = 15))) %>% 
  plotly::config(displayModeBar = FALSE)
```

```{r cond formatting example}
library(shiny)
library(tidyverse)
library(rhandsontable)

# basic user interface (not important here)
ui <- fluidPage(
  rHandsontableOutput(outputId = "ex")
)

# server side calculations
server <- function(input, output, session) {
  # create the rhandsontable object and define conditional formatting
  output$ex = renderRHandsontable({
    # create a dummy dataset
    ex_data = data.frame(id = letters[1:3],
                         attr1 = c(0.5, 0.4, 0.3),
                         attr2 = c(0.6, 0.3, 0.1))
    #create index with columns sum is equal to 1
    col_highlight <- unname(which(colSums(ex_data[c(2,3)])==1))

    rhandsontable(ex_data, col_highlight = col_highlight,
                  width = 550, height = 300) %>%
      hot_cols(renderer = "
    function(instance, td, row, col, prop, value, cellProperties) {
      Handsontable.renderers.NumericRenderer.apply(this, arguments);

      if (instance.params) {
            hcols = instance.params.col_highlight;
            hcols = hcols instanceof Array ? hcols : [hcols];
          }

      if (instance.params && hcols.includes(col)) {
        td.style.background = 'lightgreen';
      }
  }")
  })

}
shinyApp(ui,server)

```

```{r hot cond formatting}
library(shiny)
library(rhandsontable)

DF <- readRDS(system.file("extdata/lx_false_pos.rds", package = "shinylipidcountr")) %>% 
  dplyr::select(class, chemical_species, molecular_species, lipid_category,
                tidyselect::contains("all_"), tidyselect::contains("num_"))


dplyr::mutate(DF, all_under_threshold_fullms = as.character(all_under_threshold_fullms),
              all_under_threshold_ms2 = as.character(all_under_threshold_ms2),
              all_groups_under_threshold = as.character(all_groups_under_threshold),
              all_groups_under_threshold_ms2 = as.character(all_groups_under_threshold_ms2)
              )

app <- shinyApp(
  
  ui = fluidPage(
    rHandsontableOutput("hot"),
    checkboxInput(inputId = "a_u_t_fullms", label = "All under threshold [FullMS]", value = TRUE)
  ),
  
  server = function(input, output) {

    output$hot <- renderRHandsontable({
      
      myindex <- c(which(DF[,c(5)]  == TRUE),   # all_under_threshold_fullms
                   which(DF[,c(6)]  == TRUE),   # all_under_threshold_ms2
                   which(DF[,c(7)]  == TRUE),   # all_groups_under_threshold
                   which(DF[,c(8)]  == TRUE),   # all_groups_under_threshold_ms2
                   which(DF[,c(9)]  >= 16),     # num_under_threshold_fullms
                   which(DF[,c(10)]  >= 16)     # num_under_threshold_ms2
                   ) -1 
      
      rhandsontable(dplyr::mutate(DF, across(everything(), as.character)),
                    myindex = myindex
      ) %>%
        hot_cols(renderer = 
        "function(instance, td, row, col, prop, value, cellProperties) {
          
          Handsontable.renderers.TextRenderer.apply(this, arguments);
          
          if (instance.params) {
            mhrows = instance.params.myindex;
            mhrows = mhrows instanceof Array ? mhrows : [mhrows];
          }
          if (instance.params && mhrows.includes(row)) {
            td.style.background = 'pink';
          }
          if (value == 'TRUE') {
           td.style.background = 'lightblue';
          }
          if (value >= 16) {
           td.style.background = 'lightblue';
          }
          
        }"
        )
  })
    }
        )
runApp(app)
```

```{r}
false_pos <- DF[(myindex + 1),]

data2 <- data %>% filter(!species %in% false_pos$chemical_species)
```

