# read_lipidview_files----------------------------------------------------------
#' Read and merge txt.files, which are generated by LipidView
#'
#' @description read_lipidview_files() merges all available txt.files in one
#' data frame. It combines all columns by the column name.
#'
#' @param textfiles string. Path of your textfiles
#'
#' @return tibble. Merged textfiles into one tibble
#' @export
#'
#' @examples
#' list.files(path = system.file("extdata", package = "shinylipidcountr"),
#'            pattern = ".txt", full.names = TRUE) %>%
#'   read_lipidview_files()
read_lipidview_files <- function(textfiles){

  stopifnot("There are no txt.files." = length(textfiles)>0)

  as.list(textfiles) %>%
    purrr::map(read.table, header = TRUE, sep = "\t", check.names = F) %>%
    purrr::map(~ dplyr::rename(.[-1,], species = `Sample Name`)) %>%
    purrr::reduce(merge, all = TRUE, sort = FALSE) %>%
    dplyr::as_tibble()

}

# clean_lipidview_files---------------------------------------------------------
#' Clean up of LipidView txt.files
#'
#' @description Clean up of LipidView txt.files and turn it into a long format
#'  data frame. "class"-column will be created by the string inside the brackets
#'  next to the lipid species.
#'
#' @param raw_data tibble
#'
#' @return tibble
#' @export
#'
#' @examples
#' list.files(path = system.file("extdata", package = "shinylipidcountr"),
#'            pattern = ".txt", full.names = TRUE) %>%
#'   read_lipidview_files() %>%
#'   clean_lipidview_files()
clean_lipidview_files <- function(raw_data){
  # long format
  raw_data %>%
    tidyr::pivot_longer(cols = -species,
                        names_to = "sample",
                        values_to = "intensity") %>%
    # clean up
    dplyr::mutate(class = stringr::str_extract(species, "(?<=\\().+?(?=\\))"),
                  species = stringr::str_remove(species, "\\((.*?)\\)"),
                  species = ifelse(
                    class != species,
                    stringr::str_remove_all(species, paste0(class, " ")),
                    species),
                  intensity = as.numeric(intensity)) %>%
    dplyr::select(class, species, tidyr::everything())
}

################################################################################
############################## LipidXplorer part  ##############################
################################################################################

# read_lipidxplorer_files-------------------------------------------------------
#' Read csv-files, which is generated by LipidXplorer
#'
#' @param path string. Path of your csv-file
#'
#' @return tibble.
#' @export
#'
#' @examples
#' system.file("extdata", "lx-out.csv", package = "shinylipidcountr") %>%
#'   read_lipidxplorer_files()
read_lipidxplorer_files <- function(path){

  readr::read_csv(path, show_col_types = FALSE, na = c("", "None")) %>%
    dplyr::filter(Class != "###") %>%
    dplyr::select(Class, ChemicalSpecies, MolecularSpecies, LipidCategory, Mass,
                  tidyselect::starts_with("Intensity"),
                  tidyselect::starts_with("FattyAcidIntensity"))

}

# clean_lipidxplorer_files------------------------------------------------------
#' Clean up of LipidXplorer csv-files
#'
#' @param raw_data tibble
#' @param clean_samples logical. TRUE activates janitor::clean_names() for samples
#'
#' * if TRUE: "Sample 1" -> "sample_1" or "SampleOne" -> "sample_one".
#' But "Sample1" -> "sample1"!
#'
#' * if FALSE: Default. Sample name remains untouched.
#'
#' @return tibble
#' @export
#'
#' @examples
#' system.file("extdata", "lx-out.csv", package = "shinylipidcountr") %>%
#'   read_lipidxplorer_files() %>%
#'   clean_lipidxplorer_files()
clean_lipidxplorer_files <- function(raw_data, clean_samples = FALSE){

  if(clean_samples == TRUE){

    data <- raw_data %>%
      janitor::clean_names() %>%
      tidyr::pivot_longer(
        cols = c(-class, -chemical_species, -molecular_species, -lipid_category,
                 -mass),
        names_to = "sample",
        values_to = "intensity")

    # separate fullms- and ms2-intensities
    # ms1 data in column 'intensity'
    # ms2 data in column 'fa_intensity'
    data <- data %>%
      dplyr::mutate(fatty_acid_comp = ifelse(stringr::str_detect(sample, "fatty"),
                                             "fa_intensity", "intensity"),
                    sample = stringr::str_remove(sample, "fatty_acid_")) %>%
      tidyr::pivot_wider(id_cols = c(class, chemical_species, molecular_species,
                                     lipid_category, mass, sample),
                         names_from = fatty_acid_comp, values_from = intensity,
                         names_repair = "check_unique")

    # remove unnecessary strings from sample names for better reading
    data <- data %>%
      dplyr::mutate(sample = stringr::str_remove(sample, "intensity_"),
                    sample = stringr::str_remove(sample, "_s_mz_xml"))

  } else if(clean_samples == FALSE){

    data <- raw_data %>%
      tidyr::pivot_longer(
        cols = c(-Class, -ChemicalSpecies, -MolecularSpecies, -LipidCategory,
                 -Mass),
        names_to = "Sample",
        values_to = "Intensity") %>%
      janitor::clean_names()

    # separate fullms- and ms2-intensities
    # ms1 data in column 'intensity'
    # ms2 data in column 'fa_intensity'
    data <- data %>%
      dplyr::mutate(fatty_acid_comp = ifelse(stringr::str_detect(sample, "Fatty"),
                                             "fa_intensity", "intensity"),
                    sample = stringr::str_remove(sample, "FattyAcid")) %>%
      tidyr::pivot_wider(id_cols = c(class, chemical_species, molecular_species,
                                     lipid_category, mass, sample),
                         names_from = fatty_acid_comp, values_from = intensity,
                         names_repair = "check_unique")

    # remove unnecessary strings from sample names for better reading
    data <- data %>%
      dplyr::mutate(sample = stringr::str_remove(sample, "Intensity:"),
                    sample = stringr::str_remove(sample, "-s.mzXML"))

  }

  # enhance internal standard species name with 'IS', so the function
  # 'join_istd_means()' can detect internal standards
  data <- data %>%
    dplyr::mutate(chemical_species = ifelse(lipid_category == "Internal standard",
                                            paste0("IS ", chemical_species),
                                            chemical_species),
                  molecular_species = ifelse(lipid_category == "Internal standard",
                                             paste0("IS ", molecular_species),
                                             molecular_species))
  # remove class name from species for better reading
  data <- data %>%
    dplyr::rename(species = chemical_species) %>%
    dplyr::mutate(species = ifelse(class != species,
                                   stringr::str_remove_all(species, paste0(class, " ")),
                                   species))

  return(data)
}

# merge_with_lipidview----------------------------------------------------------
#' Merge data frame from LipidXplorer and LipidView.
#'
#' @param lx_data tibble. Generated before by read_lipidview_files() and clean_lipidview_files()
#' @param lv_data tibble. Generated before by read_lipidxplorer_files() and clean_lipidxplorer_files()
#'
#' @return tibble
#' @export
merge_with_lipidview <- function(lx_data, lv_data){

  lx_data_for_merging <-  lx_data %>%
    dplyr::select(class, species, sample, intensity) %>%
    dplyr::distinct()

  rbind(lv_data, lx_data_for_merging)
}
