# read_lipidview_files----------------------------------------------------------
#' Read, merge and clean txt.files, which are generated by LipidView
#'
#' @param path string. Path to your textfiles
#' @param clean_samples logical
#' * FALSE: Default. Sample name remains untouched.
#' * TRUE: activates janitor::clean_names() for samples
#' @param format string
#' * "long": Default. Prints the tibble in long-format (all samples in one col)
#' * "wide": Prints the tibble in wide-format (one sample, one col)
#'
#' @return tibble. Merged textfiles into one tibble
#' @export
#'
#' @examples
#' read_lipidview_files(system.file("extdata", package = "shinylipidcountr"))
read_lipidview_files <- function(path, clean_samples = FALSE, format = "long"){

  data <- path %>%
    list_txt_files() %>%
    read_txt_files() %>%
    clean_txt_files(clean_samples = clean_samples)

  if(format == "long"){
    data %>%
      tidyr::pivot_longer(
        cols = c(-species, -class, -scan_name),
        names_to = "sample",
        values_to = "intensity")
  } else if(format == "wide"){
    data
  }

}

# list_txt_files----------------------------------------------------------------
#' List files with '.txt'-pattern from given path and set names of each object
#'
#' @param path string. Path to your textfiles
#'
#' @return character vector
#' @export
#'
#' @examples
#' list_txt_files(system.file("extdata", package = "shinylipidcountr"))
list_txt_files <- function(path){

  list.files(path, pattern = ".txt", full.names = TRUE) %>%
    purrr::map(name_lipid_file) %>%
    unlist()
}

# name_lipid_file---------------------------------------------------------------
#' Helper function: Name a single txt.file
#'
#' @param file character. Name/path of textfile
#' @param names character vector. Vector of lipidclasses to parse out of your files
#'
#' @return character. Named version of name/path of your textfile
name_lipid_file <- function(file, names = lipid_classes){

  stringr::str_extract(file, paste0("_", names, ".txt")) %>%
    .[!is.na(.)] %>%
    stringr::str_remove("_") %>%
    stringr::str_remove(".txt")-> names(file)

  # Errormessage, if name of file is NA.
  if(is.na(names(file))){
    rlang::abort(paste0("Check filename -> ",
                        file,
                        ". Couldn't parse valid lipidname. Valid names: ",
                        paste(lipidcountr::lipid_classes, collapse = ', '),
                        ". Is your lipid class not in the list? Try 'lipid_classes <- add_lipid_class('YourLipidClass')'"
    )
    )
  }

  file
}

# read_txt_files----------------------------------------------------------------
#' Read (and merge) named txt.files, generated by LV
#'
#' @param files character vector. Vector of path/name from textfiles
#'
#' @return tibble
#' @export
#'
#' @examples
#' read_txt_files(system.file("extdata",
#'                             "yymmdd_XtrIL_ExampleData_SM.txt",
#'                             package = "lipidcountr"))
read_txt_files <- function(files){

  suppressWarnings(

    purrr::map_df(files,
                  readr::read_tsv,
                  col_types = readr::cols(),
                  skip = 1,
                  .id = "class")

  )

}

# clean_txt_files---------------------------------------------------------------
#' Clean up of LipidView txt.files
#'
#' @param rawdata tibble
#' @param clean_samples logical. FALSE activates janitor::clean_names() for samples
#'
#' * if TRUE: "Sample 1" -> "sample_1" or "SampleOne" -> "sample_one".
#' But "Sample1" -> "sample1"!
#'
#' * if FALSE: Default. Sample name remains untouched.
#'
#' @return tibble
#' @export
#'
clean_txt_files <- function(rawdata, clean_samples = FALSE){

  # General clean up of the LipidView dataframe:
  ## Get rid off unnecessary columns and strings, rename columns
  if(clean_samples == TRUE){

    janitor::clean_names(rawdata) %>%
      dplyr::filter(!stringr::str_detect(sample_name, "Sample ID")) %>%
      dplyr::select(-sample_name, -x2, -x3, -x4) %>%
      dplyr::rename("species" = x5,
                    "scan_name" = x6) %>%
      dplyr::mutate(species = stringr::str_remove_all(species, "\\+NH4"),
                    species = ifelse(
                      class != species,
                      stringr::str_remove_all(species, paste0(class, " ")),
                      species),
                    scan_name = stringr::str_remove(scan_name, "\\(-FA "),
                    scan_name = stringr::str_remove(scan_name, "\\)"),
                    scan_name = stringr::str_remove(scan_name, "\\("))

  } else if (clean_samples == FALSE){

    rawdata %>%
      dplyr::filter(!stringr::str_detect(`Sample Name`, "Sample ID")) %>%
      dplyr::select(-`Sample Name`, -...2, -...3, -...4) %>%
      dplyr::rename("species" = ...5,
                    "scan_name" = ...6) %>%
      dplyr::mutate(species = stringr::str_remove_all(species, "\\+NH4"),
                    species = ifelse(
                      class != species,
                      stringr::str_remove_all(species, paste0(class, " ")),
                      species),
                    scan_name = stringr::str_remove(scan_name, "\\(-FA "),
                    scan_name = stringr::str_remove(scan_name, "\\)"),
                    scan_name = stringr::str_remove(scan_name, "\\("))

  }

}


################################################################################
############################## LipidXplorer part  ##############################
################################################################################


# read_lipidxplorer_files-------------------------------------------------------
read_lipidxplorer_files <- function(path){

  readr::read_csv(path, show_col_types = FALSE, na = c("", "None")) %>%
    dplyr::filter(Class != "###") %>%
    dplyr::select(Class, ChemicalSpecies, MolecularSpecies, LipidCategory, Mass,
                  tidyselect::starts_with("Intensity"),
                  tidyselect::starts_with("FattyAcidIntensity"))

}

# clean_lipidxplorer_files------------------------------------------------------
clean_lipidxplorer_files <- function(rawdata, clean_samples = TRUE){

  if(clean_samples == TRUE){

    data <- rawdata %>%
      janitor::clean_names() %>%
      tidyr::pivot_longer(
        cols = c(-class, -chemical_species, -molecular_species, -lipid_category,
                 -mass),
        names_to = "sample",
        values_to = "intensity")

    # separate fullms- and ms2-intensities
    # ms1 data in column 'intensity'
    # ms2 data in column 'fa_intensity'
    data <- data %>%
      dplyr::mutate(fatty_acid_comp = ifelse(stringr::str_detect(sample, "fatty"),
                                             "fa_intensity", "intensity"),
                    sample = stringr::str_remove(sample, "fatty_acid_")) %>%
      tidyr::pivot_wider(id_cols = c(class, chemical_species, molecular_species,
                                     lipid_category, mass, sample),
                         names_from = fatty_acid_comp, values_from = intensity,
                         names_repair = "check_unique")

    # remove unnecessary strings from sample names for better reading
    data <- data %>%
      dplyr::mutate(sample = stringr::str_remove(sample, "intensity_"),
                    sample = stringr::str_remove(sample, "_s_mz_xml"))

  } else if(clean_samples == FALSE){

    data <- rawdata %>%
      tidyr::pivot_longer(
        cols = c(-Class, -ChemicalSpecies, -MolecularSpecies, -LipidCategory,
                 -Mass),
        names_to = "Sample",
        values_to = "Intensity") %>%
      janitor::clean_names()

    # separate fullms- and ms2-intensities
    # ms1 data in column 'intensity'
    # ms2 data in column 'fa_intensity'
    data <- data %>%
      dplyr::mutate(fatty_acid_comp = ifelse(stringr::str_detect(sample, "Fatty"),
                                             "fa_intensity", "intensity"),
                    sample = stringr::str_remove(sample, "FattyAcid")) %>%
      tidyr::pivot_wider(id_cols = c(class, chemical_species, molecular_species,
                                     lipid_category, mass, sample),
                         names_from = fatty_acid_comp, values_from = intensity,
                         names_repair = "check_unique")

    # remove unnecessary strings from sample names for better reading
    data <- data %>%
      dplyr::mutate(sample = stringr::str_remove(sample, "Intensity:"),
                    sample = stringr::str_remove(sample, "-s.mzXML"))

  }

  # enhance internal standard species name with 'IS', so the function
  # 'join_istd_means()' can detect internal standards
  data <- data %>%
    dplyr::mutate(chemical_species = ifelse(lipid_category == "Internal standard",
                                            paste0("IS ", chemical_species),
                                            chemical_species),
                  molecular_species = ifelse(lipid_category == "Internal standard",
                                             paste0("IS ", molecular_species),
                                             molecular_species))
  # remove class name from species for better reading
  data <- data %>%
    dplyr::rename(species = chemical_species) %>%
    dplyr::mutate(species = ifelse(class != species,
                                   stringr::str_remove_all(species, paste0(class, " ")),
                                   species))

  return(data)
}

# merge_with_lipidview----------------------------------------------------------
merge_with_lipidview <- function(lx_data, lv_data){

  lx_data_for_merging <-  lx_data %>%
    dplyr::select(class, species, sample, intensity) %>%
    dplyr::mutate(scan_name = "lx") %>%
    dplyr::distinct()

  rbind(lv_data, lx_data_for_merging)
}
